from typing import Protocol

from domain.models import Project, Task, TaskStatus


class ProjectRepository(Protocol):
    def save(self, project: Project) -> Project: ...
    def find_by_id(self, project_id: int) -> Project | None: ...
    def find_all(self) -> list[Project]: ...
    def delete(self, project_id: int) -> None: ...


class TaskRepository(Protocol):
    def save(self, task: Task) -> Task: ...
    def find_by_id(self, task_id: int) -> Task | None: ...
    def find_by_project(self, project_id: int, status: TaskStatus | None = None) -> list[Task]: ...
    def delete(self, task_id: int) -> None: ...